-- Icons directory
local dir = 'themes.icons.strings.'
local iconsColor = "#ff5555"

return {
	add 		= require(dir .. 'add'):gsub("#ffffff", iconsColor),
	awesome 		= require(dir .. 'awesome'):gsub("#ffffff", iconsColor),
	backward			= require(dir .. 'left-arrow'):gsub("#ffffff", iconsColor),
	batt_charging 		= require(dir .. 'battery-charging'):gsub("#ffffff", iconsColor),
	batt_discharging	= require(dir .. 'battery-discharge'):gsub("#ffffff", iconsColor),
	bluetooth_off 			= require(dir .. 'bluetooth-off'):gsub("#ffffff", iconsColor),
	bluetooth_on 			= require(dir .. 'bluetooth-on'):gsub("#ffffff", iconsColor),
	chain 			= require(dir .. 'chain'):gsub("#ffffff", iconsColor),
	chain_broken 			= require(dir .. 'chain-broken'):gsub("#ffffff", iconsColor),
	clearNotifications = require(dir .. 'double-check'):gsub("#ffffff", iconsColor),
	clearNotificationIndividual = require(dir .. 'check'):gsub("#ffffff", iconsColor),
	devices			= require(dir .. 'devices'):gsub("#ffffff", iconsColor),
	dot			= require(dir .. 'dot'):gsub("#ffffff", iconsColor),
	dracula			= require(dir .. 'dracula'):gsub("#ffffff", iconsColor),
	forward			= require(dir .. 'right-arrow'):gsub("#ffffff", iconsColor),
	headphones			= require(dir .. 'headphones'):gsub("#ffffff", iconsColor),
	lock 				= require(dir .. 'lock'):gsub("#ffffff", iconsColor),
	logout				= require(dir .. 'logout'):gsub("#ffffff", iconsColor),
	moon			= require(dir .. 'moon'):gsub("#ffffff", iconsColor),
	mute 				= require(dir .. 'volume-mute'):gsub("#ffffff", iconsColor),
	noNotificationsFilled = require(dir .. 'no-notifs-fill'):gsub("#ffffff", iconsColor),
	noNotifications = require(dir .. 'no-notifs'):gsub("#ffffff", iconsColor),
	notificationsFilled = require(dir .. 'notifs-fill'):gsub("#ffffff", iconsColor),
	notifications = require(dir .. 'notifs'):gsub("#ffffff", iconsColor),
	power 				= require(dir .. 'power'):gsub("#ffffff", iconsColor),
	reset 			= require(dir .. 'restart'):gsub("#ffffff", iconsColor),
	restart 			= require(dir .. 'restart'):gsub("#ffffff", iconsColor),
	search = require(dir .. 'search'):gsub("#ffffff", iconsColor),
	shield			= require(dir .. 'shield'):gsub("#ffffff", iconsColor),
	shield_off			= require(dir .. 'shield-off'):gsub("#ffffff", iconsColor),
	ship_wheel			= require(dir .. 'ship-wheel'):gsub("#ffffff", iconsColor),
	sleep 				= require(dir .. 'power-sleep'):gsub("#ffffff", iconsColor),
	toDo = require(dir .. 'circle'):gsub("#ffffff", iconsColor),
	toDoDone = require(dir .. 'check-circle'):gsub("#ffffff", iconsColor),
	volume 				= require(dir .. 'volume-high'):gsub("#ffffff", iconsColor),
	wifi_3				= require(dir .. 'wifi-3'):gsub("#ffffff", iconsColor),
	wifi_2				= require(dir .. 'wifi-2'):gsub("#ffffff", iconsColor),
	wifi_1				= require(dir .. 'wifi-1'):gsub("#ffffff", iconsColor),
	wifi_0				= require(dir .. 'wifi-0'):gsub("#ffffff", iconsColor),
	wifi_off				= require(dir .. 'wifi-off'):gsub("#ffffff", iconsColor),
	wifi_problem				= require(dir .. 'wifi-problem'):gsub("#ffffff", iconsColor),
}
