-- Icons directory
local dir = os.getenv('HOME') .. '/.config/awesome/themes/icons/icons/'


return {
	add 		= dir .. 'add.svg',
	awesome 		= dir .. 'awesome.svg',
	backward			= dir .. 'left-arrow.svg',
	batt_charging 		= dir .. 'battery-charge.svg',
	batt_discharging	= dir .. 'battery-discharge.svg',
	bluetooth_off 			= dir .. 'bluetooth-off.svg',
	bluetooth_on 			= dir .. 'bluetooth-on.svg',
	clearNotifications = dir .. 'double-check.svg',
	clearNotificationIndividual = dir .. 'check.svg',
	dot			= dir .. 'dot.svg',
	dracula			= dir .. 'dracula.svg',
	forward			= dir .. 'right-arrow.svg',
	lock 				= dir .. 'lock.svg',
	logout				= dir .. 'logout.svg',
	moon			= dir .. 'moon.svg',
	mute 				= dir .. 'volume-mute.svg',
	noNotificationsFilled = dir .. 'no-notifs-fill.svg',
	noNotifications = dir .. 'no-notifs.svg',
	notificationsFilled = dir .. 'notifs-fill.svg',
	notifications = dir .. 'notifs.svg',
	power 				= dir .. 'power.svg',
	reset 			= dir .. 'restart.svg',
	restart 			= dir .. 'restart.svg',
	shield			= dir .. 'shield.svg',
	shield_off			= dir .. 'shield-off.svg',
	ship_wheel			= dir .. 'ship-wheel.svg',
	sleep 				= dir .. 'power-sleep.svg',
	toDo = dir .. 'circle.svg',
	toDoDone = dir .. 'check-circle.svg',
	volume 				= dir .. 'volume-high.svg',
	wifi_3				= dir .. 'wifi-strong.svg',
}
