return{
	["window_gaps"]=4,
	["window_border_size"]=7,
	["bar"]={
		["right"]={
			[1]="volume",
			[2]="battery",
			[3]="network",
			[4]="notifications-bar",
			[5]="bluetooth",
			[6]="clock",
			[8]="end-session",
		},
		["colors"]={
			["focused"]="color2",
			["menu"]="color1",
			["bluetooth"]="color8",
			["clock"]="color2",
			["volume"]="color7",
			["tags"]={
				[2]="color8",
				[1]="color2",
			},
			["network"]="color4",
			["battery"]="color5",
			["notifications-bar"]="color3",
			["end-session"]="color1",
		},
		["clickableCenters"]={
			["bluetooth"]="bluetooth",
			["clock"]="cal",
			["volume"]="volume",
			["network"]="network",
			["battery"]="battery",
			["notifications-bar"]="notifications",
			["end-session"]="color1",
		},
		["left"]={
			[2]="menu",
			[1]="focused",
		},
		["center"]={
			[1]="tags",
		},
	},
	["default_programs"]={["file_manager"]="nemo",["terminal"]="kitty",["chat"]="discord",["editor"]="vscodium",["browser"]="firefox",["screenshot"]="flameshotgui",["lock"]="i3lock-fancy-multimonitor",["email"]="thunderbird",},
	["theme"]="dracula",
	["corner_radius"]=0,
	["default_states"]={[
		"mute"]="false",["numlock"]="true",["dnd"]="false",["bluetooth"]="true",
	},
	["profile_picture"]="dracula.svg",
	["background"]="ship.png",
}